### ISSUE TITLE
License inquiry 

### ISSUE THREAD

**Issue by Rudokhvist** [Goodlookinguy/pwvnrg#13]
Hello!
Sorry for contacting you about the project that seems to be not in development.
Some time ago I experienceв a need to counteract a text distortion known as "Zalgo". I looked up for a easy solution and closest thing to my needs was this repository with "anti-zalgo" script in it. I modified it for my needs and used, it's well made and helped me a lot. But then I thought that my edit of this script (main difference is that it works on any site, and also for dynamic content) my be useful for other internet users. I'd like to publish it, but there is the catch - your project have no license, so legally I don't have any rights on this code. So, my question is - maybe you will agree to license your code under some open-source license, or, if this is not acceptable for some reason, maybe you could grant to me rights to modify and redistribute at least the code in "anti-zalgo" folder?
Best Regards,
Ryzhehvost

**Comment by asterpw** [comment]
Yeah I forgot about this project.  I would license it if it was my own code
but someone else wrote that particular code and I don't really remember
who.  I'm sure they would not have minded it being licensed but it would
not be appropriate for me to license it on their behalf.

-ast

**Comment by TacoOblivion** [comment]
Commit 0068b4c and 303fc71 resolve this issue, so I'm closing this.

**Comment by Rudokhvist** [comment]
Thank you very much!
